"""add lost_item table

Revision ID: 2b82cc552c7f
Revises: eb1dd076fa0c
Create Date: 2026-09-02 10:13:23.431924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b82cc552c7f'
down_revision = 'eb1dd076fa0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('campus_location', sa.String(length=150), nullable=False),
    sa.Column('found_location_description', sa.String(length=250), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('delivered_by_name', sa.String(length=150), nullable=False),
    sa.Column('delivered_by_area', sa.String(length=150), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_items')
    # ### end Alembic commands ###
