"""add lost_item atribute storage location

Revision ID: 53b8e54e5d0e
Revises: 2b82cc552c7f
Create Date: 2026-09-02 10:49:17.384296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b8e54e5d0e'
down_revision = '2b82cc552c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_items', schema=None) as batch_op:
        batch_op.drop_column('storage_location')

    # ### end Alembic commands ###
