"""empty message

Revision ID: 99af5bce82ce
Revises: 732651ea9610
Create Date: 2026-09-21 22:54:59.233982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99af5bce82ce'
down_revision = '732651ea9610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('campus_location', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('found_location_description', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('delivered_by_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('delivered_by_area', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('storage_location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lost_items_pkey'))
    )
    # ### end Alembic commands ###
