"""Create pretriage antecedentes table

Revision ID: 0a5ce410f7be
Revises: a3bfa82e7cfb
Create Date: 2026-09-29 10:52:22.508145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5ce410f7be'
down_revision = 'a3bfa82e7cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretriage_antecedentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pretriage', sa.Integer(), nullable=False),
    sa.Column('id_antecedente', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_antecedente'], ['antecedentes.id'], ),
    sa.ForeignKeyConstraint(['id_pretriage'], ['pretriages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pretriage', 'id_antecedente', name='uq_pretriage_antecedente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pretriage_antecedentes')
    # ### end Alembic commands ###
