"""add hospital location

Revision ID: 29e5bd9f0555
Revises: 51e5a12475df
Create Date: 2026-10-08 23:12:39.604051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e5bd9f0555'
down_revision = '51e5a12475df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('address')
        batch_op.drop_column('municipality')

    # ### end Alembic commands ###
