"""correcion en relationships

Revision ID: 3e897ac26e42
Revises: 6a5909bcc5d8
Create Date: 2026-09-28 17:59:11.261789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e897ac26e42'
down_revision = '6a5909bcc5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
