"""pretriage model change

Revision ID: 47a8457b1acc
Revises: a37c8284ba81
Create Date: 2026-09-28 17:06:33.021614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a8457b1acc'
down_revision = 'a37c8284ba81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_eps', sa.Integer(), nullable=False))
        batch_op.alter_column('id_poblacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'eps', ['id_eps'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_poblacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id_eps')

    # ### end Alembic commands ###
