"""Add pretriage red flags

Revision ID: 5161bbebdbeb
Revises: b0a95e066976
Create Date: 2026-09-29 21:28:30.696613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5161bbebdbeb'
down_revision = 'b0a95e066976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pretriage_red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pretriage', sa.Integer(), nullable=False),
    sa.Column('id_bandera', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_bandera'], ['red_flags.id'], ),
    sa.ForeignKeyConstraint(['id_pretriage'], ['pretriages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pretriage', 'id_bandera', name='uq_pretriage_red_flag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pretriage_red_flags')
    # ### end Alembic commands ###
