"""empty message

Revision ID: 686987669951
Revises: 99af5bce82ce
Create Date: 2026-09-21 23:34:11.218420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686987669951'
down_revision = '99af5bce82ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_names', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_names', sa.String(length=100), nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('last_names')
        batch_op.drop_column('first_names')

    # ### end Alembic commands ###
