"""pretriage&user model change 

Revision ID: 6a5909bcc5d8
Revises: e0d360b455a8
Create Date: 2026-09-28 17:29:46.166445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5909bcc5d8'
down_revision = 'e0d360b455a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_role',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_role',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
