"""add pretriage models

Revision ID: 732651ea9610
Revises: a5c4dbe57681
Create Date: 2026-09-14 21:18:02.771473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732651ea9610'
down_revision = 'a5c4dbe57681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antecedents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('high_priority', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pretriages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_nn_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('\n            (patient_id IS NOT NULL AND user_nn_id IS NULL)\n            OR\n            (patient_id IS NULL AND user_nn_id IS NOT NULL)\n            ', name='check_pretriage_owner'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['user_nn_id'], ['usersNN.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('red_flag_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red_flag_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['red_flag_id'], ['red_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_rule_antecedents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triage_rule_id', sa.Integer(), nullable=False),
    sa.Column('antecedent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antecedent_id'], ['antecedents.id'], ),
    sa.ForeignKeyConstraint(['triage_rule_id'], ['triage_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('triage_rule_id', 'antecedent_id', name='uq_triage_rule_antecedent')
    )
    op.create_table('triage_rule_red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triage_rule_id', sa.Integer(), nullable=False),
    sa.Column('red_flag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['red_flag_id'], ['red_flags.id'], ),
    sa.ForeignKeyConstraint(['triage_rule_id'], ['triage_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('triage_rule_id', 'red_flag_id', name='uq_triage_rule_red_flag')
    )
    op.create_table('pretriage_antecedents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pretriage_id', sa.Integer(), nullable=False),
    sa.Column('antecedent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antecedent_id'], ['antecedents.id'], ),
    sa.ForeignKeyConstraint(['pretriage_id'], ['pretriages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pretriage_id', 'antecedent_id', name='uq_pretriage_antecedent')
    )
    op.create_table('pretriage_red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pretriage_id', sa.Integer(), nullable=False),
    sa.Column('red_flag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pretriage_id'], ['pretriages.id'], ),
    sa.ForeignKeyConstraint(['red_flag_id'], ['red_flags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pretriage_id', 'red_flag_id', name='uq_pretriage_red_flag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pretriage_red_flags')
    op.drop_table('pretriage_antecedents')
    op.drop_table('triage_rule_red_flags')
    op.drop_table('triage_rule_antecedents')
    op.drop_table('red_flag_questions')
    op.drop_table('pretriages')
    op.drop_table('triage_rules')
    op.drop_table('red_flags')
    op.drop_table('patients')
    op.drop_table('populations')
    op.drop_table('antecedents')
    # ### end Alembic commands ###
