"""Allow nullable EPS in pretriage

Revision ID: a3bfa82e7cfb
Revises: e74f2a147fb5
Create Date: 2026-09-29 10:16:07.603049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bfa82e7cfb'
down_revision = 'e74f2a147fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
