"""update user table

Revision ID: a5c4dbe57681
Revises: 53b8e54e5d0e
Create Date: 2026-09-10 14:55:33.479686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c4dbe57681'
down_revision = '53b8e54e5d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersNN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nn_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nn_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('document_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_identification_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['document_number'])
        batch_op.drop_column('full_name')
        batch_op.drop_column('identification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_identification_key'), ['identification'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('document_number')
        batch_op.drop_column('document_type')

    op.drop_table('usersNN')
    # ### end Alembic commands ###
