"""Remove population foreign key from red flags

Revision ID: b0a95e066976
Revises: c1495dd102b9
Create Date: 2026-09-29 19:21:29.500811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a95e066976'
down_revision = 'c1495dd102b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('red_flags_id_poblacion_fkey'), type_='foreignkey')
        batch_op.drop_column('id_poblacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_poblacion', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('red_flags_id_poblacion_fkey'), 'poblaciones', ['id_poblacion'], ['id'])

    # ### end Alembic commands ###
