"""Create poblacion red flags relationship

Revision ID: c1495dd102b9
Revises: 0a5ce410f7be
Create Date: 2026-09-29 19:17:09.786247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1495dd102b9'
down_revision = '0a5ce410f7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poblacion_red_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_poblacion', sa.Integer(), nullable=False),
    sa.Column('id_bandera', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bandera'], ['red_flags.id'], ),
    sa.ForeignKeyConstraint(['id_poblacion'], ['poblaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_poblacion', 'id_bandera', name='uq_poblacion_red_flag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poblacion_red_flags')
    # ### end Alembic commands ###
