"""add triage rules and antecedent relationships

Revision ID: cb758038fcfa
Revises: 5161bbebdbeb
Create Date: 2026-09-30 19:29:13.743915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb758038fcfa'
down_revision = '5161bbebdbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_poblacion', sa.Integer(), nullable=False),
    sa.Column('id_bandera', sa.Integer(), nullable=False),
    sa.Column('alta_prioridad', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_bandera'], ['red_flags.id'], ),
    sa.ForeignKeyConstraint(['id_poblacion'], ['poblaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_rule_antecedentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_regla', sa.Integer(), nullable=False),
    sa.Column('id_antecedente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_antecedente'], ['antecedentes.id'], ),
    sa.ForeignKeyConstraint(['id_regla'], ['triage_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_regla', 'id_antecedente', name='uq_triage_rule_antecedente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_rule_antecedentes')
    op.drop_table('triage_rules')
    # ### end Alembic commands ###
