"""pretriage model change

Revision ID: e0d360b455a8
Revises: 47a8457b1acc
Create Date: 2026-09-28 17:10:43.018202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d360b455a8'
down_revision = '47a8457b1acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_eps',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
