"""change to institution

Revision ID: e6e029dc19bc
Revises: 29e5bd9f0555
Create Date: 2026-10-08 23:21:58.279957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e029dc19bc'
down_revision = '29e5bd9f0555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institution_eps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('eps_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'eps_id', name='uq_institution_eps')
    )
    op.create_table('institution_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'service_id', name='uq_institution_service')
    )
    op.drop_table('hospital_eps')
    op.drop_table('hospital_services')
    op.drop_table('hospitals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('address', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
        sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('hospitals_pkey')),
        sa.UniqueConstraint('name', name=op.f('hospitals_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
        )
    
    op.create_table('hospital_eps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eps_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], name=op.f('hospital_eps_eps_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('hospital_eps_hospital_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hospital_eps_pkey')),
    sa.UniqueConstraint('hospital_id', 'eps_id', name=op.f('uq_hospital_eps'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    
    op.create_table('hospital_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('hospital_services_hospital_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('hospital_services_service_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('hospital_services_pkey')),
    sa.UniqueConstraint('hospital_id', 'service_id', name=op.f('uq_hospital_service'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('hospital_eps')
    op.drop_table('hospital_services')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
