"""Allow nullable population in pretriage

Revision ID: e74f2a147fb5
Revises: 3e897ac26e42
Create Date: 2026-09-29 10:11:52.846031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74f2a147fb5'
down_revision = '3e897ac26e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_poblacion',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pretriages', schema=None) as batch_op:
        batch_op.alter_column('id_poblacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
