"""add identification to users

Revision ID: eb1dd076fa0c
Revises: e17db678313f
Create Date: 2026-08-26 11:22:17.660741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1dd076fa0c'
down_revision = 'e17db678313f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['identification'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('identification')

    # ### end Alembic commands ###
